jobs:
  include:
    - name: Python without Input Directory and Output Directory Check
      os: linux
      dist: focal
      arch: amd64
      language: python
      addons:
        sbom:
          on:
            branch: main
          run_phase: after_success
          output_format: cyclonedx-xml
        deploy:
          - provider: releases
            edge: true
            file_glob: true
            file: 
              - '**/*.xml'
              - '**/*.txt'
            token: $GHTOKEN
            on:
              branch: main
          - provider: s3
            access_key_id: $ACCESS_KEY_ID
            secret_access_key: $ACCESS_KEY_SECRET
            bucket: "travis-ci-cs"
            edge: true
            upload_dir: 'result_sbom/without_dir/ele'
            on:
              branch: main
      script:
        - python hello_world.py
        - pip install -r requirements.txt
    - name: Python without Input Directory and with Output Directory Check
      os: linux
      dist: focal
      arch: amd64
      language: python
      addons:
        sbom:
          on:
            branch: main
          run_phase: after_success
          output_dir: '/python'
          output_format: cyclonedx-json
        deploy:
          - provider: releases
            edge: true
            file_glob: true
            file: 
              - 'python/*.json'
              - 'python/*.txt'
            token: $GHTOKEN
            on:
              branch: main
          - provider: s3
            access_key_id: $ACCESS_KEY_ID
            secret_access_key: $ACCESS_KEY_SECRET
            bucket: "travis-ci-cs"
            edge: true
            upload_dir: 'result_sbom/without_dir/five'
            on:
              branch: main
      script:
        - python hello_world.py
        - pip install -r requirements.txt
    - name: Python with one level Output Directory and Input directory provided
      os: linux
      dist: focal
      arch: amd64
      language: python
      addons:
        sbom:
          on:
            branch: main
          run_phase: before_script
          input_dir: '/python'
          output_dir: '/python'
          output_format: spdx-json
        deploy:
          - provider: releases
            edge: true
            file_glob: true
            file: 
              - 'python/*.json'
              - 'python/*.txt'
            token: $GHTOKEN
            on:
              branch: main
          - provider: s3
            access_key_id: $ACCESS_KEY_ID
            secret_access_key: $ACCESS_KEY_SECRET
            bucket: "travis-ci-cs"
            edge: true
            upload_dir: 'result_sbom/with_dir/two_one'
            on:
              branch: main
      script:
        - cd python
        - python hello_world.py
        - pip install -r requirements.txt
    - name: Python with two level Output Directory and Input directory provided
      os: linux
      dist: focal
      arch: amd64
      language: python
      addons:
        sbom:
          on:
            branch: main
          run_phase: before_script
          input_dir: '/python'
          output_dir: '/python/result_sbom'
          output_format: spdx-json
        deploy:
          - provider: releases
            edge: true
            file_glob: true
            file: 
              - 'result_sbom/python/*.json'
            token: $GHTOKEN
            on:
              branch: main
          - provider: s3
            access_key_id: $ACCESS_KEY_ID
            secret_access_key: $ACCESS_KEY_SECRET
            bucket: "travis-ci-cs"
            edge: true
            upload_dir: 'result_sbom/with_dir/two_two'
            on:
              branch: main
      script:
        - cd python
        - python hello_world.py
        - pip install -r requirements.txt
